env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w -X github.com/tomozo6/moray/cmd.Version=v{{.Version}}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
brews:
  - repository:
      owner: tomozo6
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/tomozo6/moray"
    description: "moray is a CLI tool to easily realize PortForwarding using SSMSessionManager of AWS."
scoops:
  - name: moray
    url_template: "https://github.com/tomozo6/moray/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/tomozo6/moray"
    description: "moray is a CLI tool to easily realize PortForwarding using SSMSessionManager of AWS."
    license: MIT
    shortcuts: [["moray.exe", "moray"]]
    repository:
      owner: tomozo6
      name: scoop-bucket
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
